# apaches Configuration
---
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Install Apache2
  apt:
    pkg: ["apache2", "libapache2-mod-php"]
    update_cache: yes
    cache_valid_time: 86400
    state: present
