# Terraform Configuration
---
- name: Install aptitude
  apt:
    name: aptitude
    update_cache: yes
    state: present
    force_apt_get: yes
  ignore_errors: yes

- name: Install prerequisites for terraform
  apt:
    pkg: ["curl", "software-properties-common", "python-apt", "python3-apt"]
    update_cache: yes
    cache_valid_time: 86400
    state: present

- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Repository
  apt_repository:
    update_cache: no
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present

# - name: Update and upgrade apt packages
#   become: true
#   apt:
#     upgrade: yes
#     update_cache: yes
#   ignore_errors: yes

- name: Install Terraform
  apt:
    name: terraform
    update_cache: yes
    state: latest
